[tool.pylint.main]
# Files or directories to be skipped. They should be base names, not paths.
ignore = [".git"]

# Files or directories matching the regular expression patterns are skipped. The
# regex matches against base names, not paths.
ignore-patterns = ["^.*~", "^.*\\.swp"]

# Use multiple processes to speed up Pylint. Specifying 0 will auto-detect the
# number of processors available to use, and will cap the count on Windows to
# avoid hangs.
jobs = 0


[tool.pylint.format]
# Regexp for a line that is allowed to be longer than the limit.
ignore-long-lines = "^\\s*(# )?<?https?://\\S+>?$"

# String used as indentation unit. This is usually "    " (4 spaces) or "\t" (1 tab).
indent-string = "\t"

# Maximum number of characters on a single line.
max-line-length = 150


[tool.pylint."messages control"]
# Disable the message, report, category or checker with the given id(s). You can
# either give multiple identifiers separated by comma (,) or put this option
# multiple times (only on the command line, not in the configuration file where
# it should appear only once). You can also use "--disable=all" to disable
# everything first and then re-enable specific checks. For example, if you want
# to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
#
# added by sidlogism: disbabling the following warnings:
#     W1201: Use lazy % formatting in logging functions (logging-not-lazy)
#     W1203: Use lazy % or % formatting in logging functions (logging-fstring-interpolation)
disable = ["logging-not-lazy","logging-fstring-interpolation"]


[tool.pylint.miscellaneous]
# List of note tags to take in consideration, separated by a comma.
notes = ["FIXME", "XXX", "TODO", "fixme", "todo", "xxx"]

